FROM postgres:11-alpine
ENV POSTGRES_USER=batch_admin
ENV POSTGRES_PASSWORD=batch_admin
ENV POSTGRES_DB=batchdata
ENV PGDATA=/usr/local/data/postgresql/data/pgdata
COPY load /docker-entrypoint-initdb.d/
RUN mkdir -p /usr/local/data && chown -R postgres:postgres /usr/local/data
USER postgres