version: '3.7'
services:

  batch-database:
    image: rwilsonebi/batch-download-db:latest
    restart: always
    ports:
      - "6082:5432"
    networks:
      batchdata:

  hasura:
    image: hasura/graphql-engine:v1.0.0-beta.2
    restart: always
    environment:
        - HASURA_GRAPHQL_DATABASE_URL=postgres://hasurauser:hasurauser@batch-database:5432/batchdata
        - HASURA_GRAPHQL_ENABLE_CONSOLE=true
        - HASURA_GRAPHQL_ENABLE_TELEMETRY=false
        - HASURA_GRAPHQL_UNAUTHORIZED_ROLE="public"
    ports:
      - "8089:8080"
    networks:
      batchdata:
            
networks:
  batchdata:

