apiVersion: v1
kind: ResourceQuota
metadata:
  name: mi-essential-genes-compute-resources
  namespace: mi-essential-genes
spec:
  hard:
    pods: "4"
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
