apiVersion: v1
kind: Service
metadata:
  name: essential-genes-dev-internal-database
  namespace: mi-essential-genes-dev
spec:
  ports:
  - port: 5432
    protocol: TCP
  selector:
    app: essential-genes-database
  type: NodePort
